// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrBzPx1oZn_xrGTBe_wJ-GJwiWL-l2f8c',
    appId: '1:471338175495:web:f96398657cf01f16406ea2',
    messagingSenderId: '471338175495',
    projectId: 'to-do-firebase-37b97',
    authDomain: 'to-do-firebase-37b97.firebaseapp.com',
    databaseURL: 'https://to-do-firebase-37b97-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-firebase-37b97.appspot.com',
    measurementId: 'G-6PFB4ED5JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPFJ5V3kz-RlU6I58jSGhorIbSrhNDJMY',
    appId: '1:471338175495:android:7fd03fac11189685406ea2',
    messagingSenderId: '471338175495',
    projectId: 'to-do-firebase-37b97',
    databaseURL: 'https://to-do-firebase-37b97-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-firebase-37b97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyxEnIPAYxYBh2t65fDjrxgeW7gSkhZ-o',
    appId: '1:471338175495:ios:950b7e1d6d522ee1406ea2',
    messagingSenderId: '471338175495',
    projectId: 'to-do-firebase-37b97',
    databaseURL: 'https://to-do-firebase-37b97-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-firebase-37b97.appspot.com',
    iosClientId: '471338175495-dm9r651seqocf5skihj2oqtije8pa5oj.apps.googleusercontent.com',
    iosBundleId: 'com.example.listify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyxEnIPAYxYBh2t65fDjrxgeW7gSkhZ-o',
    appId: '1:471338175495:ios:c5be76352b779856406ea2',
    messagingSenderId: '471338175495',
    projectId: 'to-do-firebase-37b97',
    databaseURL: 'https://to-do-firebase-37b97-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'to-do-firebase-37b97.appspot.com',
    iosClientId: '471338175495-8ss1ok3dmhk6p7nblecqv5u6ifk5eihf.apps.googleusercontent.com',
    iosBundleId: 'com.example.listify.RunnerTests',
  );
}
